import i18n from "i18next";
import { initReactI18next } from "react-i18next";
import { langService } from "../../services/storage/Factory";

i18n.use(initReactI18next).init({
  resources: {
    kz: {
      translation: {
        // auth
        signin: "Кіру",
        welcome: "Қош келдіңіз!",
        mail: "Пошта",
        inputMail: "Электрондық поштаны енгізіңіз",
        signinWith: "Немесе көмегімен кіріңіз",
        next: "Келесі",
        registerBusiness: "Ұйымды тіркеу",

        // new profile
        account: "Аккаунт",
        appLanguage: "Қосымшаның тілі",
        aboutService: "Қызмет туралы",
        help: "Көмек",
        estimateService: "Қызметті бағалау",
        safety: "Қауіпсіздік",
        logoutFromAccount: "Аккаунттан шығу",
        fillProfile: "Тез брондау үшін профиліңізді толтырыңыз",
        fill: "Толтыру",
        accountConfirm:
          "Аккаунтты растау үшін деректерді толықтыру немесе өзгерту қажет!",
        details: "Толығырақ",
        notFiled: "Толтырылмаған",
        accountWaiting: "Деректер жіберілді, растауды күтіңіз",
        organizationName: "Ұйымның атауы",
        organizationAbout: "Ұйым туралы",
        emailToLogin: "Аккаунтқа кіру үшін мекенжай",
        phone: "Байланыс үшін телефон нөмірі",
        phoneV2: "Телефон",
        site: "Сайт",
        accountSettings: "Аккаунт баптаулары",
        requiredField: "Бұл өріс міндетті",
        invalidEmail: "Электрондық пошта пішімі дұрыс емес",
        name: "Аты",
        email: "Пошта",
        invalidNumber: "Телефон нөмірі дұрыс емес",
        saved: "Сақталған",
        save: "Сақтау",

        // announcements
        type: "Түрі",
        freeWiFi: "Тегін Wi-Fi",
        privateParking: "Жеке автотұрақ",
        breakfastIncluded: "Таңғы ас тұру ақысына кіреді",
        dailyCleaning: "Бөлмені күнделікті тазалау",
        airConditioning: "Ауаны баптағыш",
        refrigerator: "Тоңазытқыш",
        television: "Теледидар",
        kettle: "Шәйнек",
        heating: "Жылу жүйесі",
        receptionAnd24HourService: "Қабылдау және тәулік бойы қызмет көрсету",
        onSitePool: "Бассейн",
        onSiteSauna: "Сауна",
        spaZone: "СПА аймағы",
        directAccessToNature: "Табиғатқа тікелей қолжетімділік",
        onSiteBonfireZones: "Ошақ аймақтары",
        excursionProgramsAndTours: "Экскурсиялық бағдарламалар және турлар",
        onSiteEntertainmentActivities: "Ойын-сауық іс-шаралары",
        onSiteChildrenPlayArea: "Балалар ойын аймағы",
        onSiteRestaurantAndBar: "Мейрамхана және бар",
        laundryAndDryCleaningServices: "Кір жуу және құрғақ тазалау қызметтері",
        washingMachine: "Кір жуғыш машина",
        iron: "Үтік",
        waterView: "Суға қараған көрініс",
        forestView: "Орманға қараған көрініс",
        gardensAndFlowerbeds: "Бағдарлар және гүлзарлар",
        kitchenUtensilsPlatesCupsCutlery:
          "Ас үй құралдары, тарелкалар, кеселер, құралдар",
        equippedPrivateKitchen: "Жабдықталған жеке ас үй",
        equippedSharedKitchen: "Жабдықталған ортақ ас үй",
        fireplace: "Камин",
        gymAndFitnessCenter: "Спорт залы және фитнес орталығы",
        medicalTreatments: "Медициналық емдеу",
        onSiteConferenceRoom: "Конференц-зал",
        equippedBeach: "Жабдықталған жағажай",
        wildBeach: "Табиғи жағажай",
        restingCanopy: "Демалыс шатырлары",
        barbecueArea: "Мангалы бар аймақ",
        tablesAndBenches: "Үстелдер мен орындықтар",
        barbecueZone: "Барбекю аймағы",
        waterAccessArea: "Суға қол жеткізу аймағы",
        tennisCourts: "Теннис корттары",
        footballField: "Футбол алаңы",
        golfCourse: "Гольф алаңы",
        beachVolleyball: "Жағажай волейболы",
        childrensPlayground: "Балалар ойын алаңы",
        ropePark: "Арқан паркі",
        routeWithSignposts: "Бағдар көрсеткіштері бар маршрут",
        mountainTrail: "Таулы жол",
        forestTrail: "Орман жолы",
        wildlifeObservationArea: "Жануарларды бақылау аймағы",
        fishingSpot: "Балық аулау орны",
        huntingSpot: "Аң аулау орны",
        mushroomPickingArea: "Саңырауқұлақ теру орны",
        berryPickingArea: "Жидек теру орны",
        equippedCampingSite: "Жабдықталған кемпинг орны",
        wildCampingSite: "Табиғи кемпинг орны",
        winterFishing: "Қысқы балық аулау",
        europeanCuisine: "Еуропа асханасы",
        easternCuisine: "Шығыс асханасы",
        kidsMenu: "Балалар мәзірі",
        vegetarianDishes: "Вегетариандық тағамдар",
        glutenAndLactoseFreeDishes: "Глютенсіз және лактозасыз тағамдар",
        dietaryMenu: "Диеталық мәзір",
        freshAndOrganicFood: "Жаңа және табиғи азық-түлік",
        kazakhNationalCuisine: "Қазақ ұлттық тағамдары",
        italianCuisine: "Итальян асханасы",
        japaneseCuisine: "Жапон асханасы",
        detoxCocktails: "Детокс коктейльдер",
        sportsNutrition: "Спорттық тағамдар",
        wineList: "Шарап мәзірі",
        outdoorSeatingTerraces: "Ашық ауада орындар (террасалар)",
        liveMusic: "Тірі музыка",
        historicalPlace: "Тарихи орын",
        museum: "Мұражай",
        naturalMonument: "Табиғи ескерткіш",
        observationArea: "Көру алаңы",
        park: "Паркі",
        monument: "Ескерткіш",
        sculpture: "Мүсін",
        castle: "Қамал",
        fortress: "Қорған",
        archaeologicalSite: "Археологиялық орын",
        resortSightseeingTour: "Курорттық экскурсиялық тур",
        abylaiKhanGladeTour: "Абылай хан алаңына экскурсия",
        bolektauMountainHike: "Болектау тауына саяхат",
        okzhetpesMountainHike: "Окжетпес тауына саяхат",
        kokchetauMountainHike: "Кокшетау тауына саяхат",
        excursion: "Экскурсия",
        busTours: "Автобус турлары",
        bodyWrap: "Оберту",
        peeling: "Пилинг",
        sauna: "Сауна",
        steamBathWithAttendant: "Парильшісімен сауна/монша",
        hydroMassageAndJacuzzi: "Гидромассажды ванна мен джакузи",
        mineralWaterPool: "Минералды су бассейні",
        mudBath: "Балшықты ванна",
        mineralBath: "Минералды ванна",
        aromatherapy: "Аромотерапия",
        classicMassage: "Классикалық массаж",
        thaiMassage: "Тай массажы",
        professionalWellnessMassage: "Кәсіби денсаулық сақтау массажы",
        meditationSession: "Медитациялық сессия",
        yogaClass: "Йога сабағы",
        facialCare: "Бет күтімі",
        bodyCare: "Дене күтімі",
        hairCare: "Шаш күтімі",
        nailCare: "Тырнақ күтімі",
        hydroMassagePool: "Гидромассажды бассейн",
        charcotShower: "Шарко душы",
        saltRoom: "Тұзды бөлме",
        thermalSpring: "Термальды бұлақ",
        rehabilitationProgram: "Реабилитациялық бағдарлама",
        fitnessClassWithTrainer: "Жаттығу сабағы тренермен",
        cardioTraining: "Кардио жаттығу",
        pilates: "Пилатес",
        relaxationAndRecreationArea: "Демалу және тынығу аймағы",
        inhalationProcedure: "Ингаляциялық процедура",
        cosmeticProcedure: "Косметикалық процедура",
        rejuvenationProgram: "Жасарту бағдарламасы",
        hammockAndLoungerZone: "Гамак және шезлонг аймағы",
        teaCeremony: "Чай рәсімі",
        quietZoneWithBackgroundMusic: "Фондық музыкамен тыныш аймақ",
        martialArtsClass: "Жауынгерлік өнер сабағы",
        specialDetoxProgram: "Арнайы детокс бағдарламасы",
        musculoskeletalSystemProgram: "Бұлшықет және сүйек жүйесі бағдарламасы",
        mudCosmeticProcedure: "Балшықты косметикалық процедура",
        therapeuticSwimming: "Емдік жүзу",
        jointTherapyApplication: "Буын терапиясы қолдану",
        turkishHammam: "Түрік хаммамы",
        privateSpaRoom: "Жеке СПА бөлмесі",
        groupMeditationSession: "Топтық медитация сессиясы",
        relaxationMassage: "Релаксациялық массаж",
        mineralSprings: "Минералды бұлақтар",
        russianBath: "Ресей моншасы",
        finnishBath: "Фин моншасы",
        turkishBath: "Түрік моншасы",
        yogaHall: "Йога залы",
        massageSalon: "Массаж салоны",
        therapeuticProgram: "Емдік бағдарлама",
        amusementPark: "Аттракциондар паркі",
        waterPark: "Су паркі",
        zoo: "Зоопарк",
        pettingZoo: "Контактты зоопарк",
        goKarting: "Картинг",
        bowling: "Боулинг",
        disco: "Дискотека",
        karaoke: "Караоке",
        party: "Кеш",
        show: "Шоу",
        concert: "Концерт",
        celebration: "Мереке",
        culturalEvent: "Мәдени іс-шара",
        souvenirShop: "Сувенир дүкені",
        souvenirAndLocalCraftShops:
          "Сувенирлер мен жергілікті қолөнер дүкендері",
        pontoonBoatWaterTours: "Понтонды қайықпен су турлары",
        attractionsAreas: "Аттракциондар аймағы",
        farm: "Ферма",
        festivalsAndFairs: "Фестивальдер мен жәрмеңкелер",
        traditionalNationalHolidays: "Дәстүрлі ұлттық мерекелер",
        exhibitions: "Көрмелер",
        craftWorkshops: "Ремескалық шеберханалар",
        quadBiking: "Төрт дөңгелекті көлікпен серуендеу",
        buggyRiding: "Багги міну",
        paragliding: "Парапланмен ұшу",
        ropeJumping: "Арқанмен секіру",
        parachuting: "Парашютпен секіру",
        jetSkiing: "Гидроциклмен серуендеу",
        horsebackRiding: "Атпен серуендеу",
        bungeeJumping: "Бунджи секіру",
        rafting: "Рафтинг",
        wakeboarding: "Вейкбординг",
        snowboardingTrails: "Сноуборд жолдары",
        skiingTrails: "Шаңғымен сырғанау жолдары",
        tubingTrails: "Тюбинг жолдары",
        sleddingTrails: "Шана жолдары",
        offRoadJeepTours: "Жолсыз джип турлары",
        rockClimbing: "Жартасқа өрмелеу",
        mountaineering: "Тауда жүру",
        iceRinks: "Мұз айдындары",
        huskySledding: "Хаски шана тебу",
        reindeerSledding: "Түйеқұстармен шана тебу",
        zorbing: "Зорбинг",
        bicycles: "Велосипедтер",
        electricScooters: "Электросамокаттар",
        snowboardsAndSkis: "Сноубордтар мен шаңғы",
        catamarans: "Катамарандар",
        boats: "Лодкалар",
        supBoards: "SUP тақталары",
        fishingGear: "Балық аулау құралдары",
        campingEquipment: "Кемпинг жабдықтары",
        carRentalWithDriver: "Жүргізушімен көлік жалға беру",
        medicalPoint: "Медициналық пункт",
        rescueServicePoint: "Құтқарушылар пункті",
        pharmacy: "Дәріхана",
        policeStation: "Полиция бөлімі",
        atm: "Банкомат",
        currencyExchangePoint: "Валютаны айырбастау пункті",
        deviceChargingArea: "Құрылғыларды зарядтау аймағы",
        freeWiFiZone: "Тегін Wi-Fi аймағы",
        taxi: "Такси",
        transferService: "Тасымалдау қызметі",
        concierge: "Консьерж",
        resortBus: "Курорт бойынша автобус аялдамалары",
      },
    },
    ru: {
      translation: {
        // auth
        signin: "Вход",
        welcome: "Добро пожаловать!",
        mail: "Почта",
        inputMail: "Введите адрес электронной почты",
        signinWith: "Или войдите с помощью",
        next: "Далее",
        registerBusiness: "Зарегистрировать организацию",

        // new profile
        account: "Аккаунт",
        appLanguage: "Язык приложения",
        aboutService: "О сервисе",
        help: "Помощь",
        estimateService: "Оценить сервис",
        safety: "Безопасность",
        logoutFromAccount: "Выйти из аккаунта",
        fillProfile: "Заполните свой профиль что бы бронировать быстрее",
        fill: "Заполнить",
        accountConfirm: "Подтвердите аккаунт что бы принимать предоплату",
        details: "Подробнее",
        notFiled: "Не заполнено",
        accountWaiting: "Данные отправлены, ожидайте подтверждение",
        organizationName: "Название организации",
        organizationAbout: "Об организации",
        emailToLogin: "Адрес для входа в в аккаунт",
        phone: "Номер телефона для связи с вами",
        contactPhone: "Номер телефона для связи",
        phoneV2: "Телефон",
        site: "Сайт",
        accountSettings: "Настройки аккаунта",
        requiredField: "Поле обязательно",
        invalidEmail: "Неверный формат почты",
        name: "Имя",
        email: "Почта",
        invalidNumber: "Некорректный номер телефона",
        saved: "Сохраненное",
        save: "Сохранить",
        description: "Описание",
        // auth accept
        confirmEmail: "Подтверждение email",
        inputCode: "Введите код из письма",
        sendCodeInfo: "Код отправлен на почту",
        invalidCode: "Неверный код",
        tooManyRequest: "Слишком много попыток, попробуйте позже",
        goToAuth: "Вернуться на страницу входа",

        // register
        password: "Пароль",
        invalidPassword: "Пароль слишком короткий",
        inputPassword: "Введите пароль",
        register: "Регистрация",
        termsOfUseText: "Регистрируясь, Вы соглашаетесь",
        termsOfUseLink: "с Условиями и Политикой конфиденциальности",
        emailBusy:
          "Почта зарегестрирована на туристическом аккаунте, измените адрес в аккаунте или укажите другой адрес",
        createPassword: "Придумайте пароль от 8 символов",
        defaultError: "Произошла ошибка",
        wrongPassword: "Неверный пароль",
        auth: "Авторизация",
        passwordFor: "Введите пароль от аккаунта",
        inputOrgName: "Введите название",
        inputDescription: "Напишите, чем вы занимаетесь",
        siteUrl: "Сайт, при наличии",
        webAddress: "Адрес сайта",
        acceptRegister: "Зарегистрировать",
        signIn: "Войти",
        forgotPassword: "Забыли пароль?",
        repeatMail: "Повторить письмо",
        repeatMailAfter: "Повторить можно через",
        // errors

        // announcements
        newAnnouncemet: "Новое обьявление",
        workingDays: "Режим работы",
        aroundClock: "Круглосуточно, без ограничений",
        monday: "Понедельник",
        tuesday: "Вторник",
        wednesday: "Среда",
        thursday: "Четверг",
        friday: "Пятница",
        saturday: "Суббота",
        sunday: "Воскресенье",
        breakTime: "Перерыв",
        breakDescription:
          "Ежедневно время, на которое запрещено бронирование. Данная информация будет учтена при бронировании услуги клиентом",
        add: "Добавить",

        serviceSchedule: "Расписание услуг",
        preview: "Просмотр",
        serviceFullDay: "Услуга длится полные сутки",
        serviceTime: "Время начала услуги",
        serviceTimeDescription: "Во сколько начинается услуга? Добавьте несколько вариантов при необходимости",
        standardDuration: "Стандартная длительность услуги",
        infoForClients: "Эта информация будет видна клиентам",
        continue: "Продолжить",

        type: "Тип",
        freeWiFi: "Бесплатный Wi-Fi",
        privateParking: "Своя парковка",
        breakfastIncluded: "Завтрак включен в стоимость проживания",
        dailyCleaning: "Ежедневная уборка помещения",
        airConditioning: "Кондиционер",
        refrigerator: "Холодильник",
        television: "Телевизор",
        kettle: "Чайник",
        heating: "Отопление",
        receptionAnd24HourService: "Ресепшен и круглосуточное обслуживание",
        onSitePool: "Бассейн на территории",
        onSiteSauna: "Сауна на территории",
        spaZone: "СПА-зона",
        directAccessToNature: "Прямой доступ к природе",
        onSiteBonfireZones: "Зоны для костров на территории",
        excursionProgramsAndTours: "Организация экскурсионных программ и туров",
        onSiteEntertainmentActivities:
          "Развлекательные мероприятия на территории",
        onSiteChildrenPlayArea: "Детская игровая зона на территории",
        onSiteRestaurantAndBar: "Ресторан и бар на территории",
        laundryAndDryCleaningServices: "Услуги прачечной химчистки",
        washingMachine: "Стиральная машина",
        iron: "Утюг",
        waterView: "С видом на водоем",
        forestView: "С видом на лес",
        gardensAndFlowerbeds: "Сады и цветочные клумбы на территории",
        kitchenUtensilsPlatesCupsCutlery:
          "Кухонная утварь, тарелки, чашки, приборы",
        equippedPrivateKitchen: "Оборудованная личная кухня",
        equippedSharedKitchen: "Оборудованная общая кухня",
        fireplace: "Камин",
        gymAndFitnessCenter: "Спортзал и фитнес-центр на территории",
        medicalTreatments: "Лечебные процедуры",
        onSiteConferenceRoom: "Конференц-зал на территории",
        equippedBeach: "Оборудованный пляж",
        wildBeach: "Дикий пляж",
        restingCanopy: "Навес для отдыха",
        barbecueArea: "Зона с мангалами",
        tablesAndBenches: "Столики и лавочки",
        barbecueZone: "Зона с барбекю",
        waterAccessArea: "Зона с доступом к воде",
        tennisCourts: "Теннисные корты",
        footballField: "Футбольное поле",
        golfCourse: "Гольф поле",
        beachVolleyball: "Пляжный волейбол",
        childrensPlayground: "Детская игровая площадка",
        ropePark: "Веревочный парк",
        routeWithSignposts: "Маршрут с указателями",
        mountainTrail: "Горная тропа",
        forestTrail: "Лесная тропа",
        wildlifeObservationArea: "Зона для наблюдения за животными",
        fishingSpot: "Место для рыбалки",
        huntingSpot: "Место для охоты",
        mushroomPickingArea: "Место для сбора грибов",
        berryPickingArea: "Место для сбора ягод",
        equippedCampingSite: "Оборудованное место для кемпинга",
        wildCampingSite: "Дикое место для кемпинга",
        winterFishing: "Зимняя рыбалка",
        europeanCuisine: "Европейская кухня",
        easternCuisine: "Восточная кухня",
        kidsMenu: "Детское меню",
        vegetarianDishes: "Вегетарианские блюда",
        glutenAndLactoseFreeDishes: "Блюда без глютена и лактозы",
        dietaryMenu: "Диетическое меню",
        freshAndOrganicFood: "Свежее и органическое питание",
        kazakhNationalCuisine: "Казахская национальная кухня",
        italianCuisine: "Итальянская кухня",
        japaneseCuisine: "Японская кухня",
        detoxCocktails: "Детокс-коктейли",
        sportsNutrition: "Спортивное питание",
        wineList: "Винная карта",
        outdoorSeatingTerraces: "Места на свежем воздухе (террасы)",
        liveMusic: "Живая музыка",
        historicalPlace: "Историческое место",
        museum: "Музей",
        naturalMonument: "Природный памятник",
        observationArea: "Обзорная площадь",
        park: "Парк",
        monument: "Памятник",
        sculpture: "Скульптура",
        castle: "Замок",
        fortress: "Крепость",
        archaeologicalSite: "Археологический объект",
        resortSightseeingTour: "Тур по достопримечательностям курорта",
        abylaiKhanGladeTour: "Тур на поляну Абылай-Хана",
        bolektauMountainHike: "Тур с подъемом в горы Болектау",
        okzhetpesMountainHike: "Тур с подъемом в горы Окжетпес",
        kokchetauMountainHike: "Тур с подъемом в горы Кокшетау",
        excursion: "Экскурсия",
        busTours: "Автобусные экскурсии",
        bodyWrap: "Обертывание",
        peeling: "Пилинг",
        sauna: "Сауна",
        steamBathWithAttendant: "Сауна/Баня с парильщиком",
        hydroMassageAndJacuzzi: "Ванна с гидромассажем и джакузи",
        mineralWaterPool: "Бассейн с минеральной водой",
        mudBath: "Грязевая ванна",
        mineralBath: "Минеральная ванна",
        aromatherapy: "Ароматерапия",
        classicMassage: "Классический массаж",
        thaiMassage: "Тайский массаж",
        professionalWellnessMassage: "Профессиональный оздоровительный массаж",
        meditationSession: "Медитационная сессия",
        yogaClass: "Занятие йогой",
        facialCare: "Уход за лицом",
        bodyCare: "Уход за телом",
        hairCare: "Уход за волосами",
        nailCare: "Уход за ногтями",
        hydroMassagePool: "Гидромассажный бассейн",
        charcotShower: "Душ Шарко",
        saltRoom: "Соляная комната",
        thermalSpring: "Термальный источник",
        rehabilitationProgram: "Реабилитационная программа",
        fitnessClassWithTrainer: "Фитнес-занятие с тренером",
        cardioTraining: "Кардио-тренировка",
        pilates: "Пилатес",
        relaxationAndRecreationArea: "Зона отдыха и релаксации",
        inhalationProcedure: "Ингаляционная процедура",
        cosmeticProcedure: "Косметологическая процедура",
        rejuvenationProgram: "Омолаживающая программа",
        hammockAndLoungerZone: "Зона с гамаком и лежаком",
        teaCeremony: "Чайная церемония",
        quietZoneWithBackgroundMusic: "Тихая зона с фоновой музыкой",
        martialArtsClass: "Занятие боевым искусством",
        specialDetoxProgram: "Специальная детокс-программа",
        musculoskeletalSystemProgram:
          "Программа для опорно-двигательной системы",
        mudCosmeticProcedure: "Косметическая процедура с грязями",
        therapeuticSwimming: "Лечебное плавание",
        jointTherapyApplication: "Лечебная аппликация для суставов",
        turkishHammam: "Турецкий хаммам",
        privateSpaRoom: "Частная СПА-комната",
        groupMeditationSession: "Групповая сессия медитации",
        relaxationMassage: "Релаксационный массаж",
        mineralSprings: "Минеральные источники",
        russianBath: "Русская баня",
        finnishBath: "Финская баня",
        turkishBath: "Турецкая баня",
        yogaHall: "Йога-зал",
        massageSalon: "Массажный салон",
        therapeuticProgram: "Лечебная программа",
        amusementPark: "Парк аттракционов",
        waterPark: "Аква-парк",
        zoo: "Зоопарк",
        pettingZoo: "Контактный зоопарк",
        goKarting: "Картинг",
        bowling: "Боулинг",
        disco: "Дискотека",
        karaoke: "Караоке",
        party: "Вечеринка",
        show: "Шоу",
        concert: "Концерт",
        celebration: "Праздник",
        culturalEvent: "Культурное мероприятие",
        souvenirShop: "Сувенирный магазин",
        souvenirAndLocalCraftShops: "Магазины сувениров и местного ремесла",
        pontoonBoatWaterTours: "Водные экскурсии на понтонном катере",
        attractionsAreas: "Площадки с аттракционами",
        farm: "Ферма",
        festivalsAndFairs: "Фестивали и ярмарки",
        traditionalNationalHolidays: "Традиционные национальные праздники",
        exhibitions: "Выставки",
        craftWorkshops: "Ремесленные мастер-классы",
        quadBiking: "Катание на квадроциклах",
        buggyRiding: "Катание на багги",
        paragliding: "Полет на параплане",
        ropeJumping: "Прыжки с веревкой (роуп-джампинг)",
        parachuting: "Парашютный спорт",
        jetSkiing: "Катание на гидроциклах",
        horsebackRiding: "Конные прогулки, катание на лошадях",
        bungeeJumping: "Прыжки с тарзанкой",
        rafting: "Рафтинг",
        wakeboarding: "Вейкбординг",
        snowboardingTrails: "Трассы для катания на сноуборде",
        skiingTrails: "Трассы для катания на лыжах",
        tubingTrails: "Трассы для тюбинга",
        sleddingTrails: "Трассы для катания на санях",
        offRoadJeepTours: "Экскурсии на внедорожниках (Джип – сафари)",
        rockClimbing: "Скалолазание",
        mountaineering: "Альпинизм",
        iceRinks: "Ледовые катки",
        huskySledding: "Катание на упряжках хаски",
        reindeerSledding: "Катание на оленьих упряжках",
        zorbing: "Зорбинг",
        bicycles: "Велосипеды",
        electricScooters: "Электросамокаты",
        snowboardsAndSkis: "Сноуборды и лыжи",
        catamarans: "Катамараны",
        boats: "Лодки",
        supBoards: "SUB-доски",
        fishingGear: "Снасти для рыбалки",
        campingEquipment: "Кемпинговое оборудование",
        carRentalWithDriver: "Авто-прокат (с водителем)",
        medicalPoint: "Медицинский пункт",
        rescueServicePoint: "Пункт спасателей",
        pharmacy: "Аптека",
        policeStation: "Полицейский участок",
        atm: "Банкомат",
        currencyExchangePoint: "Пункт обмена валют",
        deviceChargingArea: "Зона для зарядки устройств",
        freeWiFiZone: "Зона бесплатного Wi-Fi",
        taxi: "Такси",
        transferService: "Трансферт",
        concierge: "Консьерж",
        resortBus: "Автобусные остановки по курорту",
        recoveryPassword: "Востановление пароля",
        inputResetEmail:
          "Укажите почту, на которую придёт письмо для востановления пароля",
        sendMail: "Отправить письмо",
        newPassword: "Новый пароль",
        accept: "Подтвердить",
        changingPassword: "Изменение пароля",
        oldPassword: "Старый пароль",
        change: "Изменить",
        incorrectPassword: "Неверный пароль",
        changePassword: "Изменение пароля",
        changeEmail: "Изменение почты",
        deleteAccount: "Удаление аккаунта",
        inputNewEmail:
          "Введите новый адрес электронной почты, мы отправим на него письмо с подтверждением",
        accepting: "Подтверждение",
        emailIsTheSame: "Новый email не должен совпадать со старым",
        deleteAccountData:
          "Все данные аккаунта будут утеряны, вы уверены что хотите удалить аккаунт?",
        changeEmailWarning:
          "Если вы хотите удалить аккаунт что бы изменить почту для входа, это можно сделать ниже или в разделе «Безопасность» во вкладке «Смена почты»",
          deleteProfile:"Удалить аккаунт",
          changeEmailAddress: "Изменить адрес почты",
          successDelete: "Аккаунт удален",
          areYouSure: "Вы уверены что хотите выйти из аккаунта?",
          exit: "Выйти",
          cancel: "Отмена",
          // Announcement
          ad: "Обьявление",
          duration: "Длительность",
          notSpecified: "не указано",
          locationOnMap: "Местоположение на карте",
          cost: "Стоимость",
          forAdults: "Для взрослых",
          paymentForKids: "Доплата за детей",
          cashOrCard: "Оплата на месте наличными или картой",
          adults: "Взрослые",
          maxAdults: "Максимальное количество детей, которые могут воспользоваться услугой одновременно.",
          maxKids: "Максимальное кол-во детей, которые могут воспользоваться услугой одновременно.",
          kids: "Дети до 14 лет",
          permissionWithAnimals: "Можно с животными",

      },
    },
    en: {
      translation: {
        // auth
        signin: "Sign In",
        welcome: "Welcome!",
        mail: "Email",
        inputMail: "Enter your email address",
        signinWith: "Or sign in with",
        next: "Next",
        registerBusiness: "Register an organization",

        // new profile
        account: "Account",
        appLanguage: "Application Language",
        aboutService: "About the Service",
        help: "Help",
        estimateService: "Rate the Service",
        safety: "Safety",
        logoutFromAccount: "Log Out",
        fillProfile: "Complete your profile to book faster",
        fill: "Complete",
        accountConfirm:
          "To confirm your account, you need to complete or update the data!",
        details: "More details",
        notFiled: "Not filled",
        accountWaiting: "Data sent, awaiting confirmation",
        organizationName: "Organization Name",
        organizationAbout: "About the Organization",
        emailToLogin: "Email address for logging into the account",
        phone: "Phone number for contacting you",
        phoneV2: "Phone",
        site: "Website",
        accountSettings: "Account Settings",
        requiredField: "This field is required",
        invalidEmail: "Invalid email format",
        name: "Name",
        email: "Email",
        invalidNumber: "Invalid phone number",
        saved: "Saved",
        save: "Save",

        // announcements
        type: "Type",
        freeWiFi: "Free Wi-Fi",
        privateParking: "Private parking",
        breakfastIncluded: "Breakfast included in the price",
        dailyCleaning: "Daily room cleaning",
        airConditioning: "Air conditioner",
        refrigerator: "Refrigerator",
        television: "Television",
        kettle: "Kettle",
        heating: "Heating",
        receptionAnd24HourService: "Reception and 24-hour service",
        onSitePool: "Swimming pool on-site",
        onSiteSauna: "Sauna on-site",
        spaZone: "SPA zone",
        directAccessToNature: "Direct access to nature",
        onSiteBonfireZones: "Bonfire areas on-site",
        excursionProgramsAndTours: "Excursion programs and tours",
        onSiteEntertainmentActivities: "Entertainment activities on-site",
        onSiteChildrenPlayArea: "Children's play area on-site",
        onSiteRestaurantAndBar: "Restaurant and bar on-site",
        laundryAndDryCleaningServices: "Laundry and dry cleaning services",
        washingMachine: "Washing machine",
        iron: "Iron",
        waterView: "View of a waterbody",
        forestView: "View of the forest",
        gardensAndFlowerbeds: "Gardens and flowerbeds on-site",
        kitchenUtensilsPlatesCupsCutlery:
          "Kitchen utensils, plates, cups, and cutlery",
        equippedPrivateKitchen: "Equipped private kitchen",
        equippedSharedKitchen: "Equipped shared kitchen",
        fireplace: "Fireplace",
        gymAndFitnessCenter: "Gym and fitness center on-site",
        medicalTreatments: "Medical treatments",
        onSiteConferenceRoom: "Conference room on-site",
        equippedBeach: "Equipped beach",
        wildBeach: "Wild beach",
        restingCanopy: "Resting canopy",
        barbecueArea: "Barbecue area",
        tablesAndBenches: "Tables and benches",
        barbecueZone: "Barbecue zone",
        waterAccessArea: "Water access area",
        tennisCourts: "Tennis courts",
        footballField: "Football field",
        golfCourse: "Golf course",
        beachVolleyball: "Beach volleyball",
        childrensPlayground: "Children's playground",
        ropePark: "Rope park",
        routeWithSignposts: "Route with signposts",
        mountainTrail: "Mountain trail",
        forestTrail: "Forest trail",
        wildlifeObservationArea: "Wildlife observation area",
        fishingSpot: "Fishing spot",
        huntingSpot: "Hunting spot",
        mushroomPickingArea: "Mushroom picking area",
        berryPickingArea: "Berry picking area",
        equippedCampingSite: "Equipped camping site",
        wildCampingSite: "Wild camping site",
        winterFishing: "Winter fishing",
        europeanCuisine: "European Cuisine",
        easternCuisine: "Eastern Cuisine",
        kidsMenu: "Kids' Menu",
        vegetarianDishes: "Vegetarian Dishes",
        glutenAndLactoseFreeDishes: "Gluten and Lactose-Free Dishes",
        dietaryMenu: "Dietary Menu",
        freshAndOrganicFood: "Fresh and Organic Food",
        kazakhNationalCuisine: "Kazakh National Cuisine",
        italianCuisine: "Italian Cuisine",
        japaneseCuisine: "Japanese Cuisine",
        detoxCocktails: "Detox Cocktails",
        sportsNutrition: "Sports Nutrition",
        wineList: "Wine List",
        outdoorSeatingTerraces: "Outdoor Seating (Terraces)",
        liveMusic: "Live Music",
        historicalPlace: "Historical site",
        museum: "Museum",
        naturalMonument: "Natural monument",
        observationArea: "Observation area",
        park: "Park",
        monument: "Monument",
        sculpture: "Sculpture",
        castle: "Castle",
        fortress: "Fortress",
        archaeologicalSite: "Archaeological site",
        resortSightseeingTour: "Resort sightseeing tour",
        abylaiKhanGladeTour: "Abylai Khan Glade Tour",
        bolektauMountainHike: "Bolektau Mountain Hike",
        okzhetpesMountainHike: "Okzhetpes Mountain Hike",
        kokchetauMountainHike: "Kokchetau Mountain Hike",
        excursion: "Excursion",
        busTours: "Bus tours",
        bodyWrap: "Body wrap",
        peeling: "Peeling",
        sauna: "Sauna",
        steamBathWithAttendant: "Steam bath with attendant",
        hydroMassageAndJacuzzi: "Hydro massage and Jacuzzi",
        mineralWaterPool: "Mineral water pool",
        mudBath: "Mud bath",
        mineralBath: "Mineral bath",
        aromatherapy: "Aromatherapy",
        classicMassage: "Classic massage",
        thaiMassage: "Thai massage",
        professionalWellnessMassage: "Professional wellness massage",
        meditationSession: "Meditation session",
        yogaClass: "Yoga class",
        facialCare: "Facial care",
        bodyCare: "Body care",
        hairCare: "Hair care",
        nailCare: "Nail care",
        hydroMassagePool: "Hydro massage pool",
        charcotShower: "Charcot shower",
        saltRoom: "Salt room",
        thermalSpring: "Thermal spring",
        rehabilitationProgram: "Rehabilitation program",
        fitnessClassWithTrainer: "Fitness class with trainer",
        cardioTraining: "Cardio training",
        pilates: "Pilates",
        relaxationAndRecreationArea: "Relaxation and recreation area",
        inhalationProcedure: "Inhalation procedure",
        cosmeticProcedure: "Cosmetic procedure",
        rejuvenationProgram: "Rejuvenation program",
        hammockAndLoungerZone: "Hammock and lounger zone",
        teaCeremony: "Tea ceremony",
        quietZoneWithBackgroundMusic: "Quiet zone with background music",
        martialArtsClass: "Martial arts class",
        specialDetoxProgram: "Special detox program",
        musculoskeletalSystemProgram: "Musculoskeletal system program",
        mudCosmeticProcedure: "Mud cosmetic procedure",
        therapeuticSwimming: "Therapeutic swimming",
        jointTherapyApplication: "Joint therapy application",
        turkishHammam: "Turkish hammam",
        privateSpaRoom: "Private spa room",
        groupMeditationSession: "Group meditation session",
        relaxationMassage: "Relaxation massage",
        mineralSprings: "Mineral springs",
        russianBath: "Russian bath",
        finnishBath: "Finnish bath",
        turkishBath: "Turkish bath",
        yogaHall: "Yoga hall",
        massageSalon: "Massage salon",
        therapeuticProgram: "Therapeutic program",
        amusementPark: "Amusement Park",
        waterPark: "Water Park",
        zoo: "Zoo",
        pettingZoo: "Petting Zoo",
        goKarting: "Go-Karting",
        bowling: "Bowling",
        disco: "Disco",
        karaoke: "Karaoke",
        party: "Party",
        show: "Show",
        concert: "Concert",
        celebration: "Celebration",
        culturalEvent: "Cultural Event",
        souvenirShop: "Souvenir Shop",
        souvenirAndLocalCraftShops: "Souvenir and Local Craft Shops",
        pontoonBoatWaterTours: "Pontoon Boat Water Tours",
        attractionsAreas: "Attractions Areas",
        farm: "Farm",
        festivalsAndFairs: "Festivals and Fairs",
        traditionalNationalHolidays: "Traditional National Holidays",
        exhibitions: "Exhibitions",
        craftWorkshops: "Craft Workshops",
        quadBiking: "Quad Biking",
        buggyRiding: "Buggy Riding",
        paragliding: "Paragliding",
        ropeJumping: "Rope Jumping",
        parachuting: "Parachuting",
        jetSkiing: "Jet Skiing",
        horsebackRiding: "Horseback Riding",
        bungeeJumping: "Bungee Jumping",
        rafting: "Rafting",
        wakeboarding: "Wakeboarding",
        snowboardingTrails: "Snowboarding Trails",
        skiingTrails: "Skiing Trails",
        tubingTrails: "Tubing Trails",
        sleddingTrails: "Sledding Trails",
        offRoadJeepTours: "Off-Road Jeep Tours",
        rockClimbing: "Rock Climbing",
        mountaineering: "Mountaineering",
        iceRinks: "Ice Rinks",
        huskySledding: "Husky Sledding",
        reindeerSledding: "Reindeer Sledding",
        zorbing: "Zorbing",
        bicycles: "Bicycles",
        electricScooters: "Electric Scooters",
        snowboardsAndSkis: "Snowboards and Skis",
        catamarans: "Catamarans",
        boats: "Boats",
        supBoards: "SUP Boards",
        fishingGear: "Fishing Gear",
        campingEquipment: "Camping Equipment",
        carRentalWithDriver: "Car Rental with Driver",
        medicalPoint: "Medical Point",
        rescueServicePoint: "Rescue Service Point",
        pharmacy: "Pharmacy",
        policeStation: "Police Station",
        atm: "ATM",
        currencyExchangePoint: "Currency Exchange Point",
        deviceChargingArea: "Device Charging Area",
        freeWiFiZone: "Free WiFi Zone",
        taxi: "Taxi",
        transferService: "Transfer Service",
        concierge: "Concierge",
        resortBus: "Resort Bus",
      },
    },
  },
  lng: langService.hasValue() ? langService.getValue() : "ru",
  fallbackLng: "ru",

  interpolation: {
    escapeValue: false,
  },
});

export default i18n;
