# FROM node:22-alpine

# WORKDIR /app

# # Копируем package.json и yarn.lock для установки зависимостей
# COPY package.json yarn.lock ./

# RUN yarn install --frozen-lockfile

# # Копируем остальные файлы проекта
# COPY . .

# RUN yarn build

# EXPOSE 3000

# CMD ["yarn", "start:prod"]
