services:
    # Сервис для бэкенда
    backend:
        build:
            context: .
            dockerfile: Dockerfile.backend
        env_file:
            - burabay-server/.env.docker
        depends_on:
            - postgres
        ports:
            - "3000:3000"
        networks:
            - app-network
        command: ["bash", "-c", "./wait-for-it.sh postgres:5432 -- yarn start:prod"]

    # Сервис для фронтенда
    frontend:
        build:
            context: .
            dockerfile: Dockerfile.frontend
        env_file:
            - burabay-client/.env
        ports:
            - "5173:5173"
        depends_on:
            - backend
        networks:
            - app-network

    # Сервис для PostgreSQL базы данных
    postgres:
        image: postgres:latest
        env_file:
            - burabay-server/.env.docker
        networks:
            - app-network
        ports:
            - "5432:5432"

    # Nginx сервис для работы SSL
    nginx:
        image: nginx:latest
        container_name: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf # Монтирование основной конфигурации Nginx
            - ./conf.d:/etc/nginx/conf.d # Монтирование конфигурации серверов
            - ./certs:/etc/nginx/certs # Монтирование каталога с сертификатами
        ports:
            - "80:80" # HTTP
            - "443:443" # HTTPS
        depends_on:
            - frontend
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    postgres-data:
