version: "3.8"

services:
    # Сервис для бэкенда
    backend-test:
        build:
            context: .
            dockerfile: Dockerfile.backend
        env_file:
            - burabay-server/.env.docker
        depends_on:
            - postgres-test
        ports:
            - "3000:3000"
        networks:
            - app-network
        command: ["bash", "-c", "./wait-for-it.sh postgres-test:5432 -- yarn start:prod"]

    # Сервис для фронтенда
    frontend-test:
        build:
            context: .
            dockerfile: Dockerfile.frontend
        env_file:
            - burabay-client/.env
        ports:
            - "5173:5173"
        depends_on:
            - backend-test
        networks:
            - app-network

    # Сервис для PostgreSQL базы данных
    postgres-test:
        image: postgres:latest
        env_file:
            - burabay-server/.env.docker
        networks:
            - app-network
        ports:
            - "5433:5432"

networks:
    app-network:
        driver: bridge
