services:
    # Сервис для бэкенда
    backend-test:
        container_name: backend-test
        build:
            context: .
            dockerfile: Dockerfile.backend
        env_file:
            - burabay-server/.env.docker
        volumes:
            - public-data:/app/public
        depends_on:
            - postgres-test
        ports:
            - "3000:3000"
        networks:
            - app-network
        command: ["bash", "-c", "./wait-for-it.sh postgres:5432 -- yarn start:prod"]

    # Сервис для фронтенда
    frontend-test:
        container_name: frontend-test
        build:
            context: .
            dockerfile: Dockerfile.frontend
        env_file:
            - burabay-client/.env
        ports:
            - "5173:5173"
        depends_on:
            - backend-test
        networks:
            - app-network

    # Сервис для PostgreSQL базы данных
    postgres-test:
        container_name: postgres-test
        image: postgres:latest
        env_file:
            - burabay-server/.env.docker
        networks:
            - app-network
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "5433:5432"

networks:
    app-network:
        driver: bridge

volumes:
    public-data:
    postgres-data:
